version: "3.9"  # optional since v1.27.0

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      network: host
    container_name: sendwich.php
    user: dev
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
    volumes:
      - .:/var/www:delegated
      - ./.docker/php/files/override.ini:/usr/local/etc/php/conf.d/local.ini:delegated
    ports:
      - "8004:80"
    depends_on:
        - mysql
    networks:
      - internal
  mysql:
      image: mysql:8
      container_name: sendwich.mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: dev
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
      ports:
          - "3310:3306"
      networks:
          - internal

networks:
  internal:
