version: "3.9"  # optional since v1.27.0

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      network: host
    container_name: sendwich_php
    user: dev
    volumes:
      - .:/var/www:delegated
      - ./.docker/php/files/override.ini:/usr/local/etc/php/conf.d/local.ini:delegated
    ports:
        - "${DOCKER_PHP_PORT:-80}:80"
        - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    depends_on:
        - mysql
    networks:
        - internal
  mysql:
      image: mysql:8
      container_name: sendwich_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: dev
          MYSQL_DATABASE: dev
          MYSQL_USER: dev
          MYSQL_PASSWORD: dev
      ports:
          - "3310:3306"
      networks:
          - internal

networks:
  internal:
